<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Ares</title>
        <meta name="description" content="...">
        <meta name="keywords" content="...">
        
        <meta name="viewport" content="width=device-width">
		<link rel="stylesheet" href="/css/style.css">
        <link rel="stylesheet" href="/css/bootstrap.min.css">
        <link rel="stylesheet" href="/css/bootstrap-responsive.min.css">
        <link rel="stylesheet" href="/css/main.css">

        <script src="/js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->

        <!-- This code is taken from http://twitter.github.com/bootstrap/examples/hero.html -->
	<div class="header">
		<div class="header_img">
		<img class="logo" src="/images/logo.png" width="200" height="90"/>
		</div>
        <div class="navbar navbar-inverse ">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="#"><?= date()?></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li ><a href="/index">Accueil</a></li>
                            <li ><a href="/about">Clients</a></li>
                            <li><a href="/connexion">Projets</a></li>
                            <li><a href="/contact">Tâches</a></li>
                            <li><a href="/contact">Gestion du temps</a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
      
		<div >
            <div class="header_bar1" >
                <div class="container">
					 <div class="row-fluid" style="margin-top: 10px; text-align: left; font-weight: bold;">
						<div class="span4"></div><!-- Message d'accueil-->
						<div class="span2"></div>   <!-- Date - Heure -->
						<div class="span2"></div>   <!-- Rôle dans l'application-->
						<div class="span2"><a href="#"></a></div>   <!-- Déconnexion-->
					</div>
            	</div>
       	 	</div>
		</div>
	</div>
        
			<div class="row-fluid">
				<div class="span12"><?php echo $this->layout()->content ?></div>
				<div class="span12">
                <p>&copy; Projet Ares - 2013</p>
            </div>
			</div>
        <!-- /container -->

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="/js/vendor/jquery-1.9.1.min.js"><\/script>')</script>

        <script src="/js/vendor/bootstrap.min.js"></script>

        <script src="/js/plugins.js"></script>
        <script src="/js/main.js"></script>
    </body>
</html>
        